In [1]:
import pandas as pd
import numpy as np

In [18]:
veri = pd.read_excel("olimpiyat.xlsx",sheet_name="ilk")
veri

                                 isim cinsiyet  yas     boy   kilo       spor
0             Slvia Domnguez Fernndez        K   29   167.0    NaN  Basketbol
1                  Usman Edu Muhammed        E   22   169.0   78.0     Futbol
2                 Popoola Sodiq Saliu        E   21   170.0   51.0     Futbol
3           Okechukwu Godson Azubuike        E   19   170.0   68.0     Futbol
4                       Tamara Radoaj        K   28   170.0    NaN  Basketbol
5                       Julian Brandt        E   20   183.0   83.0     Futbol
6                         Sven Bender        E   27   185.0   80.0     Futbol
7            Wverton Pereira da Silva        E   28   189.0   86.0     Futbol
8                       Tijana Bokovi        K   19   193.0   82.0   Voleybol
9        Maurcio Borges Almeida Silva        E   27   199.0   99.0   Voleybol
10               Evandro Motta Guerra        E   34   207.0  106.0   Voleybol
11          Maxwell Philip "Max" Holt        E   29   208.0   90.0   Voleybol
12                       Matteo Piano        E   25   208.0  102.0   Voleybol
13              Maurcio Luiz de Souza        E   72   209.0   93.0   Voleybol
14                     Lucas Saatkamp        E   30   209.0  101.0   Voleybol
15                         Wei Qiuyue        K   27  1820.0   65.0   Voleybol
16  Bruno "Bruninho" Mossa de Rezende        E   30     NaN   76.0   Voleybol
17            Jovana Brakoevi-Kancian        K   28     NaN   82.0   Voleybol
18  Micah Makanamaikalani Christenson        E   23     NaN   86.0   Voleybol
19            Tina Alexandria Charles        K   27     NaN   88.0  Basketbol
20                 Emanuele Birarelli        E   35     NaN   95.0   Voleybol

In [19]:
veri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   isim      21 non-null     object
 1   cinsiyet  21 non-null     object
 2   yas       21 non-null     int64
 3   boy       16 non-null     float64
 4   kilo      19 non-null     float64
 5   spor      21 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [8]:
print(veri.describe())
print(veri.boy.describe()[5])
boy_ortanca=veri.boy.describe()[5]
kilo_ortanca=veri.kilo.describe()[5]

             yas          boy        kilo
count  21.000000    16.000000   19.000000
mean   28.571429   291.000000   84.789474
std    10.892986   408.058656   13.750066
min    19.000000   167.000000   51.000000
25%    23.000000   170.000000   79.000000
50%    27.000000   191.000000   86.000000
75%    29.000000   208.000000   94.000000
max    72.000000  1820.000000  106.000000
191.0

In [21]:
veri_temiz=veri.copy()
veri_temiz.boy.fillna(boy_ortanca,inplace=True)
veri_temiz.kilo.fillna(kilo_ortanca,inplace=True)
print(veri.info())
print(veri_temiz.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   isim      21 non-null     object
 1   cinsiyet  21 non-null     object
 2   yas       21 non-null     int64
 3   boy       16 non-null     float64
 4   kilo      19 non-null     float64
 5   spor      21 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   isim      21 non-null     object
 1   cinsiyet  21 non-null     object
 2   yas       21 non-null     int64
 3   boy       21 non-null     float64
 4   kilo      21 non-null     float64
 5   spor      21 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB
None